// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$7 {

    static final FunctionDescriptor exit$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle exit$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "exit",
        "(I)V",
        constants$7.exit$FUNC, false
    );
    static final FunctionDescriptor getenv$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle getenv$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "getenv",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$7.getenv$FUNC, false
    );
    static final FunctionDescriptor labs$FUNC = FunctionDescriptor.of(C_LONG,
        C_LONG
    );
    static final MethodHandle labs$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "labs",
        "(J)J",
        constants$7.labs$FUNC, false
    );
    static final FunctionDescriptor ldiv$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_LONG.withName("quot"),
        C_LONG.withName("rem")
    ),
        C_LONG,
        C_LONG
    );
    static final MethodHandle ldiv$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "ldiv",
        "(JJ)Ljdk/incubator/foreign/MemorySegment;",
        constants$7.ldiv$FUNC, false
    );
    static final FunctionDescriptor llabs$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle llabs$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "llabs",
        "(J)J",
        constants$7.llabs$FUNC, false
    );
    static final FunctionDescriptor lldiv$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_LONG_LONG.withName("quot"),
        C_LONG_LONG.withName("rem")
    ),
        C_LONG_LONG,
        C_LONG_LONG
    );
    static final MethodHandle lldiv$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "lldiv",
        "(JJ)Ljdk/incubator/foreign/MemorySegment;",
        constants$7.lldiv$FUNC, false
    );
}


