// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$51 {

    static final FunctionDescriptor spng_get_chrm_int$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_chrm_int$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_chrm_int",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$51.spng_get_chrm_int$FUNC, false
    );
    static final FunctionDescriptor spng_get_gama$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_gama$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_gama",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$51.spng_get_gama$FUNC, false
    );
    static final FunctionDescriptor spng_get_gama_int$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_gama_int$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_gama_int",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$51.spng_get_gama_int$FUNC, false
    );
    static final FunctionDescriptor spng_get_iccp$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_iccp$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_iccp",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$51.spng_get_iccp$FUNC, false
    );
    static final FunctionDescriptor spng_get_sbit$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_sbit$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_sbit",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$51.spng_get_sbit$FUNC, false
    );
    static final FunctionDescriptor spng_get_srgb$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_srgb$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_srgb",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$51.spng_get_srgb$FUNC, false
    );
}


