// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$12 {

    static final FunctionDescriptor getsubopt$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle getsubopt$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "getsubopt",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$12.getsubopt$FUNC, false
    );
    static final FunctionDescriptor grantpt$FUNC = FunctionDescriptor.of(C_INT,
        C_INT
    );
    static final MethodHandle grantpt$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "grantpt",
        "(I)I",
        constants$12.grantpt$FUNC, false
    );
    static final FunctionDescriptor initstate$FUNC = FunctionDescriptor.of(C_POINTER,
        C_INT,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle initstate$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "initstate",
        "(ILjdk/incubator/foreign/MemoryAddress;J)Ljdk/incubator/foreign/MemoryAddress;",
        constants$12.initstate$FUNC, false
    );
    static final FunctionDescriptor jrand48$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER
    );
    static final MethodHandle jrand48$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "jrand48",
        "(Ljdk/incubator/foreign/MemoryAddress;)J",
        constants$12.jrand48$FUNC, false
    );
    static final FunctionDescriptor l64a$FUNC = FunctionDescriptor.of(C_POINTER,
        C_LONG
    );
    static final MethodHandle l64a$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "l64a",
        "(J)Ljdk/incubator/foreign/MemoryAddress;",
        constants$12.l64a$FUNC, false
    );
    static final FunctionDescriptor lcong48$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle lcong48$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "lcong48",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$12.lcong48$FUNC, false
    );
}


