// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$44 {

    static final FunctionDescriptor spng_malloc_fn$FUNC = FunctionDescriptor.of(C_POINTER,
        C_LONG
    );
    static final MethodHandle spng_malloc_fn$MH = RuntimeHelper.downcallHandle(
        "(J)Ljdk/incubator/foreign/MemoryAddress;",
        constants$44.spng_malloc_fn$FUNC, false
    );
    static final FunctionDescriptor spng_realloc_fn$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle spng_realloc_fn$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;J)Ljdk/incubator/foreign/MemoryAddress;",
        constants$44.spng_realloc_fn$FUNC, false
    );
    static final FunctionDescriptor spng_calloc_fn$FUNC = FunctionDescriptor.of(C_POINTER,
        C_LONG,
        C_LONG
    );
    static final MethodHandle spng_calloc_fn$MH = RuntimeHelper.downcallHandle(
        "(JJ)Ljdk/incubator/foreign/MemoryAddress;",
        constants$44.spng_calloc_fn$FUNC, false
    );
}


