// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$47 {

    static final FunctionDescriptor spng_set_png_stream$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_set_png_stream$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_set_png_stream",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$47.spng_set_png_stream$FUNC, false
    );
    static final FunctionDescriptor spng_set_png_file$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_set_png_file$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_set_png_file",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$47.spng_set_png_file$FUNC, false
    );
    static final FunctionDescriptor spng_get_png_buffer$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_png_buffer$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_png_buffer",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$47.spng_get_png_buffer$FUNC, false
    );
    static final FunctionDescriptor spng_set_image_limits$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle spng_set_image_limits$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_set_image_limits",
        "(Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$47.spng_set_image_limits$FUNC, false
    );
    static final FunctionDescriptor spng_get_image_limits$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_image_limits$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_image_limits",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$47.spng_get_image_limits$FUNC, false
    );
    static final FunctionDescriptor spng_set_chunk_limits$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_LONG
    );
    static final MethodHandle spng_set_chunk_limits$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_set_chunk_limits",
        "(Ljdk/incubator/foreign/MemoryAddress;JJ)I",
        constants$47.spng_set_chunk_limits$FUNC, false
    );
}


