// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$43 {

    static final FunctionDescriptor funopen$x3$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle funopen$x3$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$43.funopen$x3$FUNC, false
    );
    static final FunctionDescriptor funopen$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle funopen$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "funopen",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$43.funopen$FUNC, false
    );
    static final FunctionDescriptor __sprintf_chk$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle __sprintf_chk$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "__sprintf_chk",
        "(Ljdk/incubator/foreign/MemoryAddress;IJLjdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
        constants$43.__sprintf_chk$FUNC, true
    );
    static final FunctionDescriptor __snprintf_chk$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_INT,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle __snprintf_chk$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "__snprintf_chk",
        "(Ljdk/incubator/foreign/MemoryAddress;JIJLjdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
        constants$43.__snprintf_chk$FUNC, true
    );
    static final FunctionDescriptor __vsprintf_chk$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle __vsprintf_chk$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "__vsprintf_chk",
        "(Ljdk/incubator/foreign/MemoryAddress;IJLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$43.__vsprintf_chk$FUNC, false
    );
    static final FunctionDescriptor __vsnprintf_chk$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_INT,
        C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle __vsnprintf_chk$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "__vsnprintf_chk",
        "(Ljdk/incubator/foreign/MemoryAddress;JIJLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$43.__vsnprintf_chk$FUNC, false
    );
}


