// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$18 {

    static final FunctionDescriptor bsearch_b$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_LONG,
        C_POINTER
    );
    static final MethodHandle bsearch_b$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "bsearch_b",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JJLjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$18.bsearch_b$FUNC, false
    );
    static final FunctionDescriptor cgetcap$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle cgetcap$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "cgetcap",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemoryAddress;",
        constants$18.cgetcap$FUNC, false
    );
    static final FunctionDescriptor cgetclose$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle cgetclose$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "cgetclose",
        "()I",
        constants$18.cgetclose$FUNC, false
    );
    static final FunctionDescriptor cgetent$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle cgetent$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "cgetent",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$18.cgetent$FUNC, false
    );
    static final FunctionDescriptor cgetfirst$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle cgetfirst$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "cgetfirst",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$18.cgetfirst$FUNC, false
    );
    static final FunctionDescriptor cgetmatch$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle cgetmatch$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "cgetmatch",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$18.cgetmatch$FUNC, false
    );
}


