// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$9 {

    static final FunctionDescriptor rand$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle rand$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "rand",
        "()I",
        constants$9.rand$FUNC, false
    );
    static final FunctionDescriptor srand$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle srand$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "srand",
        "(I)V",
        constants$9.srand$FUNC, false
    );
    static final FunctionDescriptor strtod$FUNC = FunctionDescriptor.of(C_DOUBLE,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle strtod$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "strtod",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)D",
        constants$9.strtod$FUNC, false
    );
    static final FunctionDescriptor strtof$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle strtof$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "strtof",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)F",
        constants$9.strtof$FUNC, false
    );
    static final FunctionDescriptor strtol$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle strtol$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "strtol",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)J",
        constants$9.strtol$FUNC, false
    );
    static final FunctionDescriptor strtoll$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle strtoll$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "strtoll",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)J",
        constants$9.strtoll$FUNC, false
    );
}


