// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$35 {

    static final FunctionDescriptor ctermid$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle ctermid$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "ctermid",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$35.ctermid$FUNC, false
    );
    static final FunctionDescriptor fdopen$FUNC = FunctionDescriptor.of(C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle fdopen$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "fdopen",
        "(ILjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$35.fdopen$FUNC, false
    );
    static final FunctionDescriptor fileno$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle fileno$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "fileno",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$35.fileno$FUNC, false
    );
    static final FunctionDescriptor pclose$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle pclose$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "pclose",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$35.pclose$FUNC, false
    );
    static final FunctionDescriptor popen$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle popen$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "popen",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$35.popen$FUNC, false
    );
    static final FunctionDescriptor __srget$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle __srget$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "__srget",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$35.__srget$FUNC, false
    );
}


