// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$46 {

    static final FunctionDescriptor spng_rw_fn$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle spng_rw_fn$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$46.spng_rw_fn$FUNC, false
    );
    static final FunctionDescriptor spng_ctx_new$FUNC = FunctionDescriptor.of(C_POINTER,
        C_INT
    );
    static final MethodHandle spng_ctx_new$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_ctx_new",
        "(I)Ljdk/incubator/foreign/MemoryAddress;",
        constants$46.spng_ctx_new$FUNC, false
    );
    static final FunctionDescriptor spng_ctx_new2$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle spng_ctx_new2$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_ctx_new2",
        "(Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemoryAddress;",
        constants$46.spng_ctx_new2$FUNC, false
    );
    static final FunctionDescriptor spng_ctx_free$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle spng_ctx_free$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_ctx_free",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$46.spng_ctx_free$FUNC, false
    );
    static final FunctionDescriptor spng_set_png_buffer$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle spng_set_png_buffer$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_set_png_buffer",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$46.spng_set_png_buffer$FUNC, false
    );
}


