// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$53 {

    static final FunctionDescriptor spng_get_unknown_chunks$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_unknown_chunks$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_unknown_chunks",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$53.spng_get_unknown_chunks$FUNC, false
    );
    static final FunctionDescriptor spng_get_offs$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_offs$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_offs",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$53.spng_get_offs$FUNC, false
    );
    static final FunctionDescriptor spng_get_exif$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_exif$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_exif",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$53.spng_get_exif$FUNC, false
    );
    static final FunctionDescriptor spng_set_ihdr$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_set_ihdr$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_set_ihdr",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$53.spng_set_ihdr$FUNC, false
    );
    static final FunctionDescriptor spng_set_plte$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_set_plte$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_set_plte",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$53.spng_set_plte$FUNC, false
    );
    static final FunctionDescriptor spng_set_trns$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_set_trns$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_set_trns",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$53.spng_set_trns$FUNC, false
    );
}


