// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class proc_rlimit_control_wakeupmon {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_INT.withName("wm_flags"),
        C_INT.withName("wm_rate")
    ).withName("proc_rlimit_control_wakeupmon");
    public static MemoryLayout $LAYOUT() {
        return proc_rlimit_control_wakeupmon.$struct$LAYOUT;
    }
    static final VarHandle wm_flags$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("wm_flags"));
    public static VarHandle wm_flags$VH() {
        return proc_rlimit_control_wakeupmon.wm_flags$VH;
    }
    public static int wm_flags$get(MemorySegment seg) {
        return (int)proc_rlimit_control_wakeupmon.wm_flags$VH.get(seg);
    }
    public static void wm_flags$set( MemorySegment seg, int x) {
        proc_rlimit_control_wakeupmon.wm_flags$VH.set(seg, x);
    }
    public static int wm_flags$get(MemorySegment seg, long index) {
        return (int)proc_rlimit_control_wakeupmon.wm_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void wm_flags$set(MemorySegment seg, long index, int x) {
        proc_rlimit_control_wakeupmon.wm_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle wm_rate$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("wm_rate"));
    public static VarHandle wm_rate$VH() {
        return proc_rlimit_control_wakeupmon.wm_rate$VH;
    }
    public static int wm_rate$get(MemorySegment seg) {
        return (int)proc_rlimit_control_wakeupmon.wm_rate$VH.get(seg);
    }
    public static void wm_rate$set( MemorySegment seg, int x) {
        proc_rlimit_control_wakeupmon.wm_rate$VH.set(seg, x);
    }
    public static int wm_rate$get(MemorySegment seg, long index) {
        return (int)proc_rlimit_control_wakeupmon.wm_rate$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void wm_rate$set(MemorySegment seg, long index, int x) {
        proc_rlimit_control_wakeupmon.wm_rate$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


