// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class rlimit {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_LONG_LONG.withName("rlim_cur"),
        C_LONG_LONG.withName("rlim_max")
    ).withName("rlimit");
    public static MemoryLayout $LAYOUT() {
        return rlimit.$struct$LAYOUT;
    }
    static final VarHandle rlim_cur$VH = $struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("rlim_cur"));
    public static VarHandle rlim_cur$VH() {
        return rlimit.rlim_cur$VH;
    }
    public static long rlim_cur$get(MemorySegment seg) {
        return (long)rlimit.rlim_cur$VH.get(seg);
    }
    public static void rlim_cur$set( MemorySegment seg, long x) {
        rlimit.rlim_cur$VH.set(seg, x);
    }
    public static long rlim_cur$get(MemorySegment seg, long index) {
        return (long)rlimit.rlim_cur$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void rlim_cur$set(MemorySegment seg, long index, long x) {
        rlimit.rlim_cur$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle rlim_max$VH = $struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("rlim_max"));
    public static VarHandle rlim_max$VH() {
        return rlimit.rlim_max$VH;
    }
    public static long rlim_max$get(MemorySegment seg) {
        return (long)rlimit.rlim_max$VH.get(seg);
    }
    public static void rlim_max$set( MemorySegment seg, long x) {
        rlimit.rlim_max$VH.set(seg, x);
    }
    public static long rlim_max$get(MemorySegment seg, long index) {
        return (long)rlimit.rlim_max$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void rlim_max$set(MemorySegment seg, long index, long x) {
        rlimit.rlim_max$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


