// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface sig_t {

    void apply(int x0);
    static MemoryAddress allocate(sig_t fi) {
        return RuntimeHelper.upcallStub(sig_t.class, fi, constants$0.sig_t$FUNC, "(I)V");
    }
    static MemoryAddress allocate(sig_t fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(sig_t.class, fi, constants$0.sig_t$FUNC, "(I)V", scope);
    }
    static sig_t ofAddress(MemoryAddress addr) {
        return (int x0) -> {
            try {
                constants$0.sig_t$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


