// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class spng_splt {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(80, C_CHAR).withName("name"),
        C_CHAR.withName("sample_depth"),
        MemoryLayout.paddingLayout(24),
        C_INT.withName("n_entries"),
        C_POINTER.withName("entries")
    ).withName("spng_splt");
    public static MemoryLayout $LAYOUT() {
        return spng_splt.$struct$LAYOUT;
    }
    public static MemorySegment name$slice(MemorySegment seg) {
        return seg.asSlice(0, 80);
    }
    static final VarHandle sample_depth$VH = $struct$LAYOUT.varHandle(byte.class, MemoryLayout.PathElement.groupElement("sample_depth"));
    public static VarHandle sample_depth$VH() {
        return spng_splt.sample_depth$VH;
    }
    public static byte sample_depth$get(MemorySegment seg) {
        return (byte)spng_splt.sample_depth$VH.get(seg);
    }
    public static void sample_depth$set( MemorySegment seg, byte x) {
        spng_splt.sample_depth$VH.set(seg, x);
    }
    public static byte sample_depth$get(MemorySegment seg, long index) {
        return (byte)spng_splt.sample_depth$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sample_depth$set(MemorySegment seg, long index, byte x) {
        spng_splt.sample_depth$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle n_entries$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("n_entries"));
    public static VarHandle n_entries$VH() {
        return spng_splt.n_entries$VH;
    }
    public static int n_entries$get(MemorySegment seg) {
        return (int)spng_splt.n_entries$VH.get(seg);
    }
    public static void n_entries$set( MemorySegment seg, int x) {
        spng_splt.n_entries$VH.set(seg, x);
    }
    public static int n_entries$get(MemorySegment seg, long index) {
        return (int)spng_splt.n_entries$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void n_entries$set(MemorySegment seg, long index, int x) {
        spng_splt.n_entries$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle entries$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("entries")));
    public static VarHandle entries$VH() {
        return spng_splt.entries$VH;
    }
    public static MemoryAddress entries$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)spng_splt.entries$VH.get(seg);
    }
    public static void entries$set( MemorySegment seg, MemoryAddress x) {
        spng_splt.entries$VH.set(seg, x);
    }
    public static MemoryAddress entries$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)spng_splt.entries$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void entries$set(MemorySegment seg, long index, MemoryAddress x) {
        spng_splt.entries$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


