// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class __darwin_x86_debug_state64 {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_LONG_LONG.withName("__dr0"),
        C_LONG_LONG.withName("__dr1"),
        C_LONG_LONG.withName("__dr2"),
        C_LONG_LONG.withName("__dr3"),
        C_LONG_LONG.withName("__dr4"),
        C_LONG_LONG.withName("__dr5"),
        C_LONG_LONG.withName("__dr6"),
        C_LONG_LONG.withName("__dr7")
    ).withName("__darwin_x86_debug_state64");
    public static MemoryLayout $LAYOUT() {
        return __darwin_x86_debug_state64.$struct$LAYOUT;
    }
    static final VarHandle __dr0$VH = $struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("__dr0"));
    public static VarHandle __dr0$VH() {
        return __darwin_x86_debug_state64.__dr0$VH;
    }
    public static long __dr0$get(MemorySegment seg) {
        return (long)__darwin_x86_debug_state64.__dr0$VH.get(seg);
    }
    public static void __dr0$set( MemorySegment seg, long x) {
        __darwin_x86_debug_state64.__dr0$VH.set(seg, x);
    }
    public static long __dr0$get(MemorySegment seg, long index) {
        return (long)__darwin_x86_debug_state64.__dr0$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __dr0$set(MemorySegment seg, long index, long x) {
        __darwin_x86_debug_state64.__dr0$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __dr1$VH = $struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("__dr1"));
    public static VarHandle __dr1$VH() {
        return __darwin_x86_debug_state64.__dr1$VH;
    }
    public static long __dr1$get(MemorySegment seg) {
        return (long)__darwin_x86_debug_state64.__dr1$VH.get(seg);
    }
    public static void __dr1$set( MemorySegment seg, long x) {
        __darwin_x86_debug_state64.__dr1$VH.set(seg, x);
    }
    public static long __dr1$get(MemorySegment seg, long index) {
        return (long)__darwin_x86_debug_state64.__dr1$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __dr1$set(MemorySegment seg, long index, long x) {
        __darwin_x86_debug_state64.__dr1$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __dr2$VH = $struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("__dr2"));
    public static VarHandle __dr2$VH() {
        return __darwin_x86_debug_state64.__dr2$VH;
    }
    public static long __dr2$get(MemorySegment seg) {
        return (long)__darwin_x86_debug_state64.__dr2$VH.get(seg);
    }
    public static void __dr2$set( MemorySegment seg, long x) {
        __darwin_x86_debug_state64.__dr2$VH.set(seg, x);
    }
    public static long __dr2$get(MemorySegment seg, long index) {
        return (long)__darwin_x86_debug_state64.__dr2$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __dr2$set(MemorySegment seg, long index, long x) {
        __darwin_x86_debug_state64.__dr2$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __dr3$VH = $struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("__dr3"));
    public static VarHandle __dr3$VH() {
        return __darwin_x86_debug_state64.__dr3$VH;
    }
    public static long __dr3$get(MemorySegment seg) {
        return (long)__darwin_x86_debug_state64.__dr3$VH.get(seg);
    }
    public static void __dr3$set( MemorySegment seg, long x) {
        __darwin_x86_debug_state64.__dr3$VH.set(seg, x);
    }
    public static long __dr3$get(MemorySegment seg, long index) {
        return (long)__darwin_x86_debug_state64.__dr3$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __dr3$set(MemorySegment seg, long index, long x) {
        __darwin_x86_debug_state64.__dr3$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __dr4$VH = $struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("__dr4"));
    public static VarHandle __dr4$VH() {
        return __darwin_x86_debug_state64.__dr4$VH;
    }
    public static long __dr4$get(MemorySegment seg) {
        return (long)__darwin_x86_debug_state64.__dr4$VH.get(seg);
    }
    public static void __dr4$set( MemorySegment seg, long x) {
        __darwin_x86_debug_state64.__dr4$VH.set(seg, x);
    }
    public static long __dr4$get(MemorySegment seg, long index) {
        return (long)__darwin_x86_debug_state64.__dr4$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __dr4$set(MemorySegment seg, long index, long x) {
        __darwin_x86_debug_state64.__dr4$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __dr5$VH = $struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("__dr5"));
    public static VarHandle __dr5$VH() {
        return __darwin_x86_debug_state64.__dr5$VH;
    }
    public static long __dr5$get(MemorySegment seg) {
        return (long)__darwin_x86_debug_state64.__dr5$VH.get(seg);
    }
    public static void __dr5$set( MemorySegment seg, long x) {
        __darwin_x86_debug_state64.__dr5$VH.set(seg, x);
    }
    public static long __dr5$get(MemorySegment seg, long index) {
        return (long)__darwin_x86_debug_state64.__dr5$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __dr5$set(MemorySegment seg, long index, long x) {
        __darwin_x86_debug_state64.__dr5$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __dr6$VH = $struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("__dr6"));
    public static VarHandle __dr6$VH() {
        return __darwin_x86_debug_state64.__dr6$VH;
    }
    public static long __dr6$get(MemorySegment seg) {
        return (long)__darwin_x86_debug_state64.__dr6$VH.get(seg);
    }
    public static void __dr6$set( MemorySegment seg, long x) {
        __darwin_x86_debug_state64.__dr6$VH.set(seg, x);
    }
    public static long __dr6$get(MemorySegment seg, long index) {
        return (long)__darwin_x86_debug_state64.__dr6$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __dr6$set(MemorySegment seg, long index, long x) {
        __darwin_x86_debug_state64.__dr6$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __dr7$VH = $struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("__dr7"));
    public static VarHandle __dr7$VH() {
        return __darwin_x86_debug_state64.__dr7$VH;
    }
    public static long __dr7$get(MemorySegment seg) {
        return (long)__darwin_x86_debug_state64.__dr7$VH.get(seg);
    }
    public static void __dr7$set( MemorySegment seg, long x) {
        __darwin_x86_debug_state64.__dr7$VH.set(seg, x);
    }
    public static long __dr7$get(MemorySegment seg, long index) {
        return (long)__darwin_x86_debug_state64.__dr7$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __dr7$set(MemorySegment seg, long index, long x) {
        __darwin_x86_debug_state64.__dr7$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


