// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class __sigaction {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.unionLayout(
            C_POINTER.withName("__sa_handler"),
            C_POINTER.withName("__sa_sigaction")
        ).withName("__sigaction_u"),
        C_POINTER.withName("sa_tramp"),
        C_INT.withName("sa_mask"),
        C_INT.withName("sa_flags")
    ).withName("__sigaction");
    public static MemoryLayout $LAYOUT() {
        return __sigaction.$struct$LAYOUT;
    }
    public static MemorySegment __sigaction_u$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    static final FunctionDescriptor sa_tramp$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle sa_tramp$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;IILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        __sigaction.sa_tramp$FUNC, false
    );
    public interface sa_tramp {

        void apply(jdk.incubator.foreign.MemoryAddress x0, int x1, int x2, jdk.incubator.foreign.MemoryAddress x3, jdk.incubator.foreign.MemoryAddress x4);
        static MemoryAddress allocate(sa_tramp fi) {
            return RuntimeHelper.upcallStub(sa_tramp.class, fi, __sigaction.sa_tramp$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;IILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V");
        }
        static MemoryAddress allocate(sa_tramp fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(sa_tramp.class, fi, __sigaction.sa_tramp$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;IILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V", scope);
        }
        static sa_tramp ofAddress(MemoryAddress addr) {
            return (jdk.incubator.foreign.MemoryAddress x0, int x1, int x2, jdk.incubator.foreign.MemoryAddress x3, jdk.incubator.foreign.MemoryAddress x4) -> {
                try {
                    __sigaction.sa_tramp$MH.invokeExact((Addressable)addr, x0, x1, x2, x3, x4);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle sa_tramp$VH = MemoryHandles.asAddressVarHandle($struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("sa_tramp")));
    public static VarHandle sa_tramp$VH() {
        return __sigaction.sa_tramp$VH;
    }
    public static MemoryAddress sa_tramp$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)__sigaction.sa_tramp$VH.get(seg);
    }
    public static void sa_tramp$set( MemorySegment seg, MemoryAddress x) {
        __sigaction.sa_tramp$VH.set(seg, x);
    }
    public static MemoryAddress sa_tramp$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)__sigaction.sa_tramp$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sa_tramp$set(MemorySegment seg, long index, MemoryAddress x) {
        __sigaction.sa_tramp$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static sa_tramp sa_tramp (MemorySegment segment) {
        return sa_tramp.ofAddress(sa_tramp$get(segment));
    }
    static final VarHandle sa_mask$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("sa_mask"));
    public static VarHandle sa_mask$VH() {
        return __sigaction.sa_mask$VH;
    }
    public static int sa_mask$get(MemorySegment seg) {
        return (int)__sigaction.sa_mask$VH.get(seg);
    }
    public static void sa_mask$set( MemorySegment seg, int x) {
        __sigaction.sa_mask$VH.set(seg, x);
    }
    public static int sa_mask$get(MemorySegment seg, long index) {
        return (int)__sigaction.sa_mask$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sa_mask$set(MemorySegment seg, long index, int x) {
        __sigaction.sa_mask$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sa_flags$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("sa_flags"));
    public static VarHandle sa_flags$VH() {
        return __sigaction.sa_flags$VH;
    }
    public static int sa_flags$get(MemorySegment seg) {
        return (int)__sigaction.sa_flags$VH.get(seg);
    }
    public static void sa_flags$set( MemorySegment seg, int x) {
        __sigaction.sa_flags$VH.set(seg, x);
    }
    public static int sa_flags$get(MemorySegment seg, long index) {
        return (int)__sigaction.sa_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sa_flags$set(MemorySegment seg, long index, int x) {
        __sigaction.sa_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


