// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface atexit$x0 {

    void apply();
    static MemoryAddress allocate(atexit$x0 fi) {
        return RuntimeHelper.upcallStub(atexit$x0.class, fi, constants$5.atexit$x0$FUNC, "()V");
    }
    static MemoryAddress allocate(atexit$x0 fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(atexit$x0.class, fi, constants$5.atexit$x0$FUNC, "()V", scope);
    }
    static atexit$x0 ofAddress(MemoryAddress addr) {
        return () -> {
            try {
                constants$5.atexit$x0$MH.invokeExact((Addressable)addr);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


