// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$33 {

    static final FunctionDescriptor rewind$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle rewind$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "rewind",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$33.rewind$FUNC, false
    );
    static final FunctionDescriptor scanf$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle scanf$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "scanf",
        "(Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
        constants$33.scanf$FUNC, true
    );
    static final FunctionDescriptor setbuf$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle setbuf$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "setbuf",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$33.setbuf$FUNC, false
    );
    static final FunctionDescriptor setvbuf$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT,
        C_LONG
    );
    static final MethodHandle setvbuf$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "setvbuf",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;IJ)I",
        constants$33.setvbuf$FUNC, false
    );
    static final FunctionDescriptor sprintf$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle sprintf$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "sprintf",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
        constants$33.sprintf$FUNC, true
    );
    static final FunctionDescriptor sscanf$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle sscanf$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "sscanf",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
        constants$33.sscanf$FUNC, true
    );
}


