// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$25 {

    static final FunctionDescriptor qsort_r$__compar$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle qsort_r$__compar$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$25.qsort_r$__compar$FUNC, false
    );
    static final FunctionDescriptor qsort_r$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_LONG,
        C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle qsort_r$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "qsort_r",
        "(Ljdk/incubator/foreign/MemoryAddress;JJLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$25.qsort_r$FUNC, false
    );
    static final FunctionDescriptor radixsort$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle radixsort$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "radixsort",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        constants$25.radixsort$FUNC, false
    );
    static final FunctionDescriptor rpmatch$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle rpmatch$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "rpmatch",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$25.rpmatch$FUNC, false
    );
    static final FunctionDescriptor sradixsort$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle sradixsort$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "sradixsort",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        constants$25.sradixsort$FUNC, false
    );
}


