// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$39 {

    static final FunctionDescriptor vsnprintf$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle vsnprintf$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "vsnprintf",
        "(Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$39.vsnprintf$FUNC, false
    );
    static final FunctionDescriptor vsscanf$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle vsscanf$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "vsscanf",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$39.vsscanf$FUNC, false
    );
    static final FunctionDescriptor dprintf$FUNC = FunctionDescriptor.of(C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle dprintf$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "dprintf",
        "(ILjdk/incubator/foreign/MemoryAddress;[Ljava/lang/Object;)I",
        constants$39.dprintf$FUNC, true
    );
    static final FunctionDescriptor vdprintf$FUNC = FunctionDescriptor.of(C_INT,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle vdprintf$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "vdprintf",
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$39.vdprintf$FUNC, false
    );
    static final FunctionDescriptor getdelim$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle getdelim$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "getdelim",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)J",
        constants$39.getdelim$FUNC, false
    );
    static final FunctionDescriptor getline$FUNC = FunctionDescriptor.of(C_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle getline$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "getline",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)J",
        constants$39.getline$FUNC, false
    );
}


