// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$26 {

    static final FunctionDescriptor sranddev$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle sranddev$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "sranddev",
        "()V",
        constants$26.sranddev$FUNC, false
    );
    static final FunctionDescriptor srandomdev$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle srandomdev$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "srandomdev",
        "()V",
        constants$26.srandomdev$FUNC, false
    );
    static final FunctionDescriptor reallocf$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle reallocf$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "reallocf",
        "(Ljdk/incubator/foreign/MemoryAddress;J)Ljdk/incubator/foreign/MemoryAddress;",
        constants$26.reallocf$FUNC, false
    );
    static final FunctionDescriptor strtonum$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_LONG_LONG,
        C_POINTER
    );
    static final MethodHandle strtonum$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "strtonum",
        "(Ljdk/incubator/foreign/MemoryAddress;JJLjdk/incubator/foreign/MemoryAddress;)J",
        constants$26.strtonum$FUNC, false
    );
    static final FunctionDescriptor strtoq$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle strtoq$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "strtoq",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)J",
        constants$26.strtoq$FUNC, false
    );
    static final FunctionDescriptor strtouq$FUNC = FunctionDescriptor.of(C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle strtouq$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "strtouq",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)J",
        constants$26.strtouq$FUNC, false
    );
}


