// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$48 {

    static final FunctionDescriptor spng_set_chunk_limits$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_LONG
    );
    static final MethodHandle spng_set_chunk_limits$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_set_chunk_limits",
        "(Ljdk/incubator/foreign/MemoryAddress;JJ)I",
        constants$48.spng_set_chunk_limits$FUNC, false
    );
    static final FunctionDescriptor spng_get_chunk_limits$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_chunk_limits$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_chunk_limits",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$48.spng_get_chunk_limits$FUNC, false
    );
    static final FunctionDescriptor spng_set_crc_action$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle spng_set_crc_action$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_set_crc_action",
        "(Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$48.spng_set_crc_action$FUNC, false
    );
    static final FunctionDescriptor spng_set_option$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle spng_set_option$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_set_option",
        "(Ljdk/incubator/foreign/MemoryAddress;II)I",
        constants$48.spng_set_option$FUNC, false
    );
    static final FunctionDescriptor spng_get_option$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle spng_get_option$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_option",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$48.spng_get_option$FUNC, false
    );
    static final FunctionDescriptor spng_decoded_image_size$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle spng_decoded_image_size$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_decoded_image_size",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$48.spng_decoded_image_size$FUNC, false
    );
}


