// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$16 {

    static final FunctionDescriptor unlockpt$FUNC = FunctionDescriptor.of(C_INT,
        C_INT
    );
    static final MethodHandle unlockpt$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "unlockpt",
        "(I)I",
        constants$16.unlockpt$FUNC, false
    );
    static final FunctionDescriptor unsetenv$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle unsetenv$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "unsetenv",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$16.unsetenv$FUNC, false
    );
    static final FunctionDescriptor arc4random$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle arc4random$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "arc4random",
        "()I",
        constants$16.arc4random$FUNC, false
    );
    static final FunctionDescriptor arc4random_addrandom$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT
    );
    static final MethodHandle arc4random_addrandom$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "arc4random_addrandom",
        "(Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$16.arc4random_addrandom$FUNC, false
    );
    static final FunctionDescriptor arc4random_buf$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_LONG
    );
    static final MethodHandle arc4random_buf$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "arc4random_buf",
        "(Ljdk/incubator/foreign/MemoryAddress;J)V",
        constants$16.arc4random_buf$FUNC, false
    );
    static final FunctionDescriptor arc4random_stir$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle arc4random_stir$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "arc4random_stir",
        "()V",
        constants$16.arc4random_stir$FUNC, false
    );
}


