// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$49 {

    static final FunctionDescriptor spng_decode_image$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_INT,
        C_INT
    );
    static final MethodHandle spng_decode_image$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_decode_image",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JII)I",
        constants$49.spng_decode_image$FUNC, false
    );
    static final FunctionDescriptor spng_decode_scanline$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle spng_decode_scanline$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_decode_scanline",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$49.spng_decode_scanline$FUNC, false
    );
    static final FunctionDescriptor spng_decode_row$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle spng_decode_row$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_decode_row",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$49.spng_decode_row$FUNC, false
    );
    static final FunctionDescriptor spng_decode_chunks$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle spng_decode_chunks$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_decode_chunks",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$49.spng_decode_chunks$FUNC, false
    );
    static final FunctionDescriptor spng_get_row_info$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_row_info$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_row_info",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$49.spng_get_row_info$FUNC, false
    );
    static final FunctionDescriptor spng_encode_image$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_INT,
        C_INT
    );
    static final MethodHandle spng_encode_image$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_encode_image",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JII)I",
        constants$49.spng_encode_image$FUNC, false
    );
}


