// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$50 {

    static final FunctionDescriptor spng_encode_scanline$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle spng_encode_scanline$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_encode_scanline",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$50.spng_encode_scanline$FUNC, false
    );
    static final FunctionDescriptor spng_encode_row$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle spng_encode_row$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_encode_row",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$50.spng_encode_row$FUNC, false
    );
    static final FunctionDescriptor spng_encode_chunks$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle spng_encode_chunks$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_encode_chunks",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$50.spng_encode_chunks$FUNC, false
    );
    static final FunctionDescriptor spng_get_ihdr$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_ihdr$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_ihdr",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$50.spng_get_ihdr$FUNC, false
    );
    static final FunctionDescriptor spng_get_plte$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_plte$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_plte",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$50.spng_get_plte$FUNC, false
    );
    static final FunctionDescriptor spng_get_trns$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle spng_get_trns$MH = RuntimeHelper.downcallHandle(
        spng_h.LIBRARIES, "spng_get_trns",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$50.spng_get_trns$FUNC, false
    );
}


