// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class spng_chunk {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_LONG.withName("offset"),
        C_INT.withName("length"),
        MemoryLayout.sequenceLayout(4, C_CHAR).withName("type"),
        C_INT.withName("crc"),
        MemoryLayout.paddingLayout(32)
    ).withName("spng_chunk");
    public static MemoryLayout $LAYOUT() {
        return spng_chunk.$struct$LAYOUT;
    }
    static final VarHandle offset$VH = $struct$LAYOUT.varHandle(long.class, MemoryLayout.PathElement.groupElement("offset"));
    public static VarHandle offset$VH() {
        return spng_chunk.offset$VH;
    }
    public static long offset$get(MemorySegment seg) {
        return (long)spng_chunk.offset$VH.get(seg);
    }
    public static void offset$set( MemorySegment seg, long x) {
        spng_chunk.offset$VH.set(seg, x);
    }
    public static long offset$get(MemorySegment seg, long index) {
        return (long)spng_chunk.offset$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void offset$set(MemorySegment seg, long index, long x) {
        spng_chunk.offset$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle length$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("length"));
    public static VarHandle length$VH() {
        return spng_chunk.length$VH;
    }
    public static int length$get(MemorySegment seg) {
        return (int)spng_chunk.length$VH.get(seg);
    }
    public static void length$set( MemorySegment seg, int x) {
        spng_chunk.length$VH.set(seg, x);
    }
    public static int length$get(MemorySegment seg, long index) {
        return (int)spng_chunk.length$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void length$set(MemorySegment seg, long index, int x) {
        spng_chunk.length$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment type$slice(MemorySegment seg) {
        return seg.asSlice(12, 4);
    }
    static final VarHandle crc$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("crc"));
    public static VarHandle crc$VH() {
        return spng_chunk.crc$VH;
    }
    public static int crc$get(MemorySegment seg) {
        return (int)spng_chunk.crc$VH.get(seg);
    }
    public static void crc$set( MemorySegment seg, int x) {
        spng_chunk.crc$VH.set(seg, x);
    }
    public static int crc$get(MemorySegment seg, long index) {
        return (int)spng_chunk.crc$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void crc$set(MemorySegment seg, long index, int x) {
        spng_chunk.crc$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


