// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class spng_phys {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_INT.withName("ppu_x"),
        C_INT.withName("ppu_y"),
        C_CHAR.withName("unit_specifier"),
        MemoryLayout.paddingLayout(24)
    ).withName("spng_phys");
    public static MemoryLayout $LAYOUT() {
        return spng_phys.$struct$LAYOUT;
    }
    static final VarHandle ppu_x$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("ppu_x"));
    public static VarHandle ppu_x$VH() {
        return spng_phys.ppu_x$VH;
    }
    public static int ppu_x$get(MemorySegment seg) {
        return (int)spng_phys.ppu_x$VH.get(seg);
    }
    public static void ppu_x$set( MemorySegment seg, int x) {
        spng_phys.ppu_x$VH.set(seg, x);
    }
    public static int ppu_x$get(MemorySegment seg, long index) {
        return (int)spng_phys.ppu_x$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ppu_x$set(MemorySegment seg, long index, int x) {
        spng_phys.ppu_x$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle ppu_y$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("ppu_y"));
    public static VarHandle ppu_y$VH() {
        return spng_phys.ppu_y$VH;
    }
    public static int ppu_y$get(MemorySegment seg) {
        return (int)spng_phys.ppu_y$VH.get(seg);
    }
    public static void ppu_y$set( MemorySegment seg, int x) {
        spng_phys.ppu_y$VH.set(seg, x);
    }
    public static int ppu_y$get(MemorySegment seg, long index) {
        return (int)spng_phys.ppu_y$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ppu_y$set(MemorySegment seg, long index, int x) {
        spng_phys.ppu_y$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle unit_specifier$VH = $struct$LAYOUT.varHandle(byte.class, MemoryLayout.PathElement.groupElement("unit_specifier"));
    public static VarHandle unit_specifier$VH() {
        return spng_phys.unit_specifier$VH;
    }
    public static byte unit_specifier$get(MemorySegment seg) {
        return (byte)spng_phys.unit_specifier$VH.get(seg);
    }
    public static void unit_specifier$set( MemorySegment seg, byte x) {
        spng_phys.unit_specifier$VH.set(seg, x);
    }
    public static byte unit_specifier$get(MemorySegment seg, long index) {
        return (byte)spng_phys.unit_specifier$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void unit_specifier$set(MemorySegment seg, long index, byte x) {
        spng_phys.unit_specifier$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


