// Generated by jextract

package org.libspng;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface spng_calloc_fn {

    jdk.incubator.foreign.MemoryAddress apply(long x0, long x1);
    static MemoryAddress allocate(spng_calloc_fn fi) {
        return RuntimeHelper.upcallStub(spng_calloc_fn.class, fi, constants$44.spng_calloc_fn$FUNC, "(JJ)Ljdk/incubator/foreign/MemoryAddress;");
    }
    static MemoryAddress allocate(spng_calloc_fn fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(spng_calloc_fn.class, fi, constants$44.spng_calloc_fn$FUNC, "(JJ)Ljdk/incubator/foreign/MemoryAddress;", scope);
    }
    static spng_calloc_fn ofAddress(MemoryAddress addr) {
        return (long x0, long x1) -> {
            try {
                return (jdk.incubator.foreign.MemoryAddress)constants$45.spng_calloc_fn$MH.invokeExact((Addressable)addr, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


